[ 2025-04-09 19:17:54,726 ] 97 werkzeug INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.30.27.52:8080
[ 2025-04-09 19:17:54,726 ] 97 werkzeug INFO - [33mPress CTRL+C to quit[0m
[ 2025-04-09 19:18:47,949 ] 97 werkzeug INFO - 127.0.0.1 - - [09/Apr/2025 19:18:47] "GET / HTTP/1.1" 200 -
[ 2025-04-09 19:18:47,982 ] 97 werkzeug INFO - 127.0.0.1 - - [09/Apr/2025 19:18:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
[ 2025-04-09 19:18:49,861 ] 97 werkzeug INFO - 127.0.0.1 - - [09/Apr/2025 19:18:49] "GET /predictdata HTTP/1.1" 200 -
[ 2025-04-09 19:18:59,534 ] 875 app ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\src\pipeline\predict_pipeline.py", line 16, in predict
    df = self.data_ingestor.fetch_daily_stock_data(symbol=stock_symbol, api_key=os.getenv("ALPHAVANTAGE_API_KEY"))
                                                                                ^^
NameError: name 'os' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\app.py", line 23, in predict_datapoint
    result = pipeline.predict(symbol, task_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\src\pipeline\predict_pipeline.py", line 39, in predict
    raise CustomException(e, sys)
src.exception.CustomException: Error occured in python script name [C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\src\pipeline\predict_pipeline.py] line number [16] error message[name 'os' is not defined]
[ 2025-04-09 19:18:59,540 ] 97 werkzeug INFO - 127.0.0.1 - - [09/Apr/2025 19:18:59] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
