[ 2025-04-09 19:22:28,138 ] 97 werkzeug INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:8080
 * Running on http://10.30.27.52:8080
[ 2025-04-09 19:22:28,138 ] 97 werkzeug INFO - [33mPress CTRL+C to quit[0m
[ 2025-04-09 19:22:35,585 ] 97 werkzeug INFO - 127.0.0.1 - - [09/Apr/2025 19:22:35] "GET /predictdata HTTP/1.1" 200 -
[ 2025-04-09 19:22:37,898 ] 97 werkzeug INFO - 127.0.0.1 - - [09/Apr/2025 19:22:37] "GET /predictdata HTTP/1.1" 200 -
[ 2025-04-09 19:22:40,621 ] 97 werkzeug INFO - 127.0.0.1 - - [09/Apr/2025 19:22:40] "GET / HTTP/1.1" 200 -
[ 2025-04-09 19:22:41,604 ] 97 werkzeug INFO - 127.0.0.1 - - [09/Apr/2025 19:22:41] "GET /predictdata HTTP/1.1" 200 -
[ 2025-04-09 19:22:47,362 ] 875 app ERROR - Exception on /predictdata [POST]
Traceback (most recent call last):
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\src\components\data_ingestion.py", line 45, in fetch_daily_stock_data
    raise CustomException("Failed to retrieve daily data from API", sys)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\src\exception.py", line 17, in __init__
    self.error_message=error_message_detail(error_message,error_detail=error_detail)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\src\exception.py", line 6, in error_message_detail
    file_name=exc_tb.tb_frame.f_code.co_filename
              ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'tb_frame'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\src\pipeline\predict_pipeline.py", line 18, in predict
    df = self.data_ingestor.fetch_daily_stock_data(symbol=stock_symbol, api_key=os.getenv("ALPHAVANTAGE_API_KEY"))
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\src\components\data_ingestion.py", line 73, in fetch_daily_stock_data
    raise CustomException(e, sys)
src.exception.CustomException: Error occured in python script name [C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\src\components\data_ingestion.py] line number [45] error message['NoneType' object has no attribute 'tb_frame']

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\env\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\env\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\env\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\env\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\app.py", line 21, in predict_datapoint
    result = pipeline.predict(stock_symbol, task_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\src\pipeline\predict_pipeline.py", line 41, in predict
    raise CustomException(e, sys)
src.exception.CustomException: Error occured in python script name [C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\src\pipeline\predict_pipeline.py] line number [18] error message[Error occured in python script name [C:\Users\V_Tushar.Jadhav\Desktop\AI\Stock_project\Stock_Price_Prediction\src\components\data_ingestion.py] line number [45] error message['NoneType' object has no attribute 'tb_frame']]
[ 2025-04-09 19:22:47,367 ] 97 werkzeug INFO - 127.0.0.1 - - [09/Apr/2025 19:22:47] "[35m[1mPOST /predictdata HTTP/1.1[0m" 500 -
